name: Unity Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  BUILD_OUTPUT_PATH: build

jobs:

  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - WebGL
          - StandaloneOSX
          # - Android
          # - iOs
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Current folder path
        run: pwd

      - name: Directory content before build
        run: ls -al

      - uses: actions/cache@v3
        with:
          path: Library/
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-

      - name: Version from env.variable
        run: echo "${{ env.UNITY_VERSION }}"

      - name: Directory content before build
        run: ls -al
        
      - name: Tree structure
        run: |
          sudo apt-get install tree
          tree ${{ env.BUILD_OUTPUT_PATH }}

      # https://github.com/game-ci/unity-builder/releases/
      - name: Building game
        uses: game-ci/unity-builder@v4
        with:
          # Platform that the build should target.
          targetPlatform: ${{ matrix.targetPlatform }}
          # Path where the builds should be stored.
          buildsPath: ${{ env.BUILD_OUTPUT_PATH}}
          buildName: ${{ env.BUILD_NAME}}
          # Custom parameters to configure the build.
          # Parameters must start with a hyphen (-) and may be followed by a value (without hyphen). Parameters without a value will be considered booleans (with a value of true).
          # customParameters: '-nographics' # <--- This is the important bit [https://github.com/webbertakken/unity-builder/issues/153]

      - name: Directory content after build
        run: ls -al

      - name: Tree structure
        run: |
          sudo apt-get install tree
          tree ${{ env.BUILD_OUTPUT_PATH }}

      - name: Unity - Return License
        uses: game-ci/unity-return-license@v2.0.0
          
      # Output
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_OUTPUT_PATH }}/${{ matrix.targetPlatform }}
